name: Check release tag

on: push

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_last_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: panachainy/github-auto-release
          excludes: prerelease, draft
      - name: Latest version
        run: echo "Lastest version ${{ steps.get_last_version.outputs.release }}"
      - name: Current version
        run: echo "Current version $(./version.sh)"
      - name: Check version is more than previous versions
        run: echo ${{ steps.get_last_version.outputs.release }} | sed 's/v//'
      - run: echo $(./version.sh) | sed 's/v//'
