name: Check release tag

on: push

jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - run: echo $(./version.sh)
      - run: echo ${{ github.event.release.tag_name }}
      - id: get_last_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: panachainy/github-auto-release
          excludes: prerelease, draft
      - run: echo ${{ steps.get_last_version.outputs.release }}
