name: Release Drafter

on: push

jobs:
  create_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version from app
        run: echo "VERSION=$(./version.sh)" >> $GITHUB_ENV
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - run: echo $(./version.sh)
